[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bearing_pipeline"
version = "0.1.0"
dependencies = [
    "polars",
    "pyarrow",
    "duckdb",
    "kagglehub",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.ruff.lint]
ignore = [
    "DTZ001",  # datetime.datetime() called without a tzinfo argument
    "DTZ007",  # Naive datetime constructed using datetime.strptime() without %z
]
select = [
    "E", "W", "F", "I", "UP", 
    "D",   # Enable docstring checks
]

[tool.ruff.lint.pydocstyle]
convention = "google"
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["D104"]
"tests/*.py" = ["D"]