[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bearing_pipeline"
version = "0.1.0"
dependencies = [
    "polars",
    "pyarrow",
    "duckdb",
    "kagglehub",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.ruff.lint]
ignore = [
    "DTZ001",  # datetime.datetime() called without a tzinfo argument
    "DTZ007",  # Naive datetime constructed using datetime.strptime() without %z
]